### ISSUE TITLE
AWS EC2 환경에서 쿨엔조이 날짜 파싱 문제 발생

### ISSUE THREAD

**Issue by chaiminwoo0223** [jijijig/Albeobsa-Backend#19]
```
spring-boot-app  | 2024-06-01T08:57:27.740Z ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
spring-boot-app  | 
spring-boot-app  | skhu.jijijig.exception.CrawlingProcessException: 크롤링 중 오류 발생: 데이터 추출 중 오류 발생: Invalid value for MonthOfYear (valid values 1 - 12): 24
spring-boot-app  | 	at skhu.jijijig.service.CrawlingService.crawlWebsite(CrawlingService.java:146) ~[!/:0.0.1-SNAPSHOT]
spring-boot-app  | 	at skhu.jijijig.service.CrawlingService.performCrawlingForCoolenjoy(CrawlingService.java:80) ~[!/:0.0.1-SNAPSHOT]
spring-boot-app  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
spring-boot-app  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
spring-boot-app  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385) ~[spring-tx-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at skhu.jijijig.service.CrawlingService$$SpringCGLIB$$0.performCrawlingForCoolenjoy(<generated>) ~[!/:0.0.1-SNAPSHOT]
spring-boot-app  | 	at skhu.jijijig.service.CrawlingService.scheduleCrawlingTasks(CrawlingService.java:44) ~[!/:0.0.1-SNAPSHOT]
spring-boot-app  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
spring-boot-app  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
spring-boot-app  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:713) ~[spring-aop-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at skhu.jijijig.service.CrawlingService$$SpringCGLIB$$0.scheduleCrawlingTasks(<generated>) ~[!/:0.0.1-SNAPSHOT]
spring-boot-app  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
spring-boot-app  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
spring-boot-app  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.12.3.jar!/:1.12.3]
spring-boot-app  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.4.jar!/:6.1.4]
spring-boot-app  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
spring-boot-app  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[na:na]
spring-boot-app  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
spring-boot-app  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
spring-boot-app  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
spring-boot-app  | 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
spring-boot-app  | 

```

**Comment by chaiminwoo0223** [comment]
1.24.06.01에서 06이 아니라, 24를 저장하고 있습니다.
2.월별 데이터(01, 02, ... ,12)를 저장할 수 있도록 수정하겠습니다.

**Comment by chaiminwoo0223** [comment]
다음달로 넘어갔을 때, 오늘 날짜, 어제 날짜 그리고 이전 날짜를 정확하게 파싱합니다.
